### PR TITLE
Bookstore: Use Redux in React components

### PR DESCRIPTION
**Pull request by wassimchakib**
In this feature, I:

- [x]  Integrated Redux login into React App using `react-redux` library
- [x] Imported Provider with the configureStore and used it in main component
- [x] Displayed list of books from Redux Store
- [x] Added new book / Remove / Show Categories status using `useDispatch` with action

### CODE REVIEW

**Review by FrederickMih — COMMENTED** [review]
## Hi :raising_hand:  @wassimchakib, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Some sections in your README file doesn't have content:

Screenshot from 2022-12-13 16-48-03
You'll kindly provide content to render the README.md file descriptive.

- Some checks are failing in your repo making it unprofessional 
Screenshot from 2022-12-13 16-51-44
You'll kindly need to fix it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by wassimchakib** [comment]
@FrederickMih Thank you for the suggestions. Please try to focus on the project requirement more than the content, My linters are passing + Readme file sections are empty because the project is not finished yet, and I'm planning to finish once I have an idea what is this project about and its features. If you have optional suggestion like filling readme file, please use [optional] comment for that.
Thanks for understanding. 👍

**Comment by prolajumokeoni** [comment]
Hi @wassimchakib 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have 1-3 potential features in the future features section of your readme

It would be better to add personalized content to the remaining section of your readme, this will make your readme more professional  👍🏿 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by wassimchakib** [comment]
@prolajumokeoni you guys must be trolling right? How I'm supposed to know the potential future features? Also there is a concept called DRY. **SO INSTEAD OF REPEATING AND CHANGING README FILE EVERY SINGLE TIME IN EVERY SINGLE FEATURE**. I will change it once I finish the project. and Readme File are meant for people who want to use my project and it's mostly filled once the whole project is finished!. Thanks

**Comment by mirouhml** [comment]
Hi @wassimchakib, 

## Invalid Code Review Request

I understand that what we're requesting is frustrating for you, but please know that those are the requirements and we're just following them, kindly follow what the previous reviewers told you so we can review your project, to summarize what you need to do:

- [x] All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your README, kindly add them, the only **optional** section is FAQ.
- [x] Make sure to add the section **Future Features**, including 1-3 potential features to be added, I know you mentioned that you don't know what to include there, but please try to at least add one potential feature you'd like to see in your website, it can be anything.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by mirouhml — APPROVED** [review]
# APPROVED 🟢

Hi @wassimchakib, 

Thanks for editing your README, and good job on finishing the project on the first try! Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Optional suggestions

- [x] When you add a new a book this is how the progress bar looks on my side:

  image
  
  Not sure if it's intended or not just wanted to point it out!


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wassimchakib** [comment]
@mirouhml Thank you for mentioning that, I gave the completion status a default value of 0% and the chapter a default value of 'Chapter 1' whenever a book is added.

**Comment by mirouhml** [comment]
@wassimchakib good to know, best of luck with your next projects!

**Pull request merged**
